accepted = [
    "GPL-3.0",
    "LGPL-3.0",
    "LGPL-2.1",
    "AGPL-3.0",
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "LicenseRef-UFL-1.0",
    "MPL-2.0",
    "FTL",
    "Ubuntu-font-1.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
    "zlib-acknowledgement",
    "X11",
    "CC-BY-SA-4.0",
]
targets = ["x86_64-unknown-linux-gnu", "aarch64-linux-android"]
workarounds = ["ring"]
filter-noassertion = true
