[package]
name = "filepaths"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
shared.workspace = true

dirs = "6"
const_format = "0.2.34"